from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Quiz(models.Model):
    """Quiz model representing a quiz generated from a YouTube video.
    
    A quiz is created by processing a YouTube video's audio transcript
    through AI to generate questions and answers. Each quiz belongs to
    a specific user and contains multiple questions.
    """
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='quizzes')
    title = models.CharField(max_length=200)
    description = models.TextField()
    video_url = models.URLField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "Quizzes"
        ordering = ['-created_at']

    def __str__(self):
        """String representation of the quiz."""
        return self.title


class Question(models.Model):
    """Question model representing a single quiz question.
    
    Each question belongs to a quiz and contains a question text,
    multiple choice options, and the correct answer. Questions are
    generated by AI from video transcript content.
    """
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='questions')
    question_title = models.TextField()
    question_options = models.JSONField()
    answer = models.CharField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['id']

    def __str__(self):
        """
        Returns:
            str: Question ID and truncated question text.
        """
        return f"Question {self.id}: {self.question_title[:50]}..."
